# Generated by Django 3.2.15 on 2022-11-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fitnessgraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.CharField(choices=[(3, '体操'), (4, '卓球'), (5, '野球')], max_length=100)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('day', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Fitnesspulldown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.CharField(max_length=100)),
                ('metz', models.FloatField(default=0)),
            ],
        ),
    ]
