# Generated by Django 3.2.15 on 2022-10-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fitnessgraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.CharField(max_length=100)),
                ('metz', models.IntegerField(blank=True, null=True)),
                ('day', models.DateField()),
            ],
        ),
    ]
